Remove wait for the Language-Element from FullSubmissionPage
- Removed for testing purposes, to identify the cause of the
NoSuchElementException: "Cannot locate element with text: eng - English"
etc.